[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[project]
name = "wastewater-network"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "CheesyChocolate", email = "dev@behnamlal.xyz" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "pulp>=2.7.0",
  "networkx>=3.0",
  "matplotlib>=3.5.0",
  "numpy>=1.20.0",
]

[project.urls]
Documentation = "https://github.com/CheesyChocolate/wastewater-network#readme"
Issues = "https://github.com/CheesyChocolate/wastewater-network/issues"
Source = "https://github.com/CheesyChocolate/wastewater-network"

[tool.hatch.version]
path = "src/__about__.py"

[project.scripts]
wastewater-solver = "src.modules.cli:main"

[tool.hatch.envs.default]
installer = "uv"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/wastewater_network tests}"

[tool.coverage.run]
source_pkgs = ["wastewater_network", "tests"]
branch = true
parallel = true
omit = [
  "src/wastewater_network/__about__.py",
]

[tool.coverage.paths]
wastewater_network = ["src/wastewater_network", "*/wastewater-network/src/wastewater_network"]
tests = ["tests", "*/wastewater-network/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
